import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Blockchain Warriors",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" type="image/svg+xml" href="/logo.png" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=ZCOOL+KuaiLe&display=swap"
        />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Shojumaru&display=swap"
          rel="stylesheet"
        ></link>
      </head>
      <body className={inter.className}>
        {children}
        <script
          src="https://kit.fontawesome.com/b4e92aef63.js"
          crossOrigin="anonymous"
        ></script>
      </body>
    </html>
  );
}
